# Generated by Django 3.0.8 on 2020-07-14 23:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0002_auto_20200715_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloger',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 23, 40, 45, 323941, tzinfo=utc)),
        ),
    ]
